version: "3.8"

services:

  beerapi:
    build:
      context: .
      args:
        user: martin
        uid: 1000
    image: beerapi:latest
    container_name: beerapi
    volumes:
      - ./beerapi:/beerapi
    ports:
      - "8000:8000"

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    ports:
     - "3306:3306"
    volumes:
     - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: beerapi
      MYSQL_ROOT_PASSWORD: heslo
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql


networks:
  beerapi:
    driver: bridge