version: "3.8"

services:

  beerapi_server:
    build:
      context: .
    image: beerapi:latest
    container_name: beerapi_server
    volumes:
      - ./beerapi:/beerapi
    ports:
      - "8000:8000"
    depends_on: 
      - mysql_db

  beerapi_utility:
    build:
      context: .
    image: beerapi:latest
    container_name: beerapi_utility
    volumes:
      - ./beerapi:/beerapi
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    ports:
     - "3306:3306"
    volumes:
     - ./mysql_data:/var/lib/mysql
     - ./init.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_DATABASE: beerapi
      MYSQL_ROOT_PASSWORD: heslo
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
